version: "3"
services:
  api:
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SERVER_PORT=9090
      - DB_SERVER=db:5432
      - DB_PASS=password
      - DB_USER=postgres
      - DB_NAME=whereabouts
      - PGDATA=/var/lib/postgresql/data/pgdata
      - SPRING_PROFILES_ACTIVE=postgres
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DB_SERVER=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=whereabouts
      - PGDATA=/var/lib/postgresql/data/pgdata

