apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: whereabouts-api
  labels:
    app: whereabouts-api
spec:
  replicas: 2
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: whereabouts-api
  template:
    metadata:
      labels:
        app: whereabouts-api
    spec:
      containers:
        - name: whereabouts-api
          image: 926803513772.dkr.ecr.eu-west-2.amazonaws.com/omic/whereabouts-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          resources:
            limits:
              cpu: 360m
              memory: "1024Mi"
            requests:
              cpu: 180m
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 70
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "cloud-dev"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: database_password
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: database_username
            - name: DB_SERVER
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: rds_instance_endpoint
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: whereabouts-api-rds-dev
                  key: database_name
