apiVersion: v1
kind: Service
metadata:
  name: whereabouts-api-svc
  namespace: whereabouts-dev
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
  selector:
    app: whereabouts-api
