---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: whereabouts-api-preprod.service.justice.gov.uk
  namespace: whereabouts-api-preprod
spec:
  secretName: whereabouts-api-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: 'whereabouts-api-preprod.service.justice.gov.uk'
  acme:
    config:
    - domains:
      - 'whereabouts-api-preprod.service.justice.gov.uk'
      dns01:
        provider: route53-cloud-platform
